# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"/\n\x0cLoginRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"9\n\rTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t\" \n\x0fValidateRequest\x12\r\n\x05token\x18\x01 \x01(\t\"R\n\x10ValidateResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\r\n\x05login\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x10\n\x08is_valid\x18\x04 \x01(\x08\"B\n\x11\x43reateUserRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\")\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05login\x18\x02 \x01(\t2\xbd\x01\n\x0e\x41uthNavigation\x12\x30\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.TokenResponse\x12>\n\rValidateToken\x12\x15.auth.ValidateRequest\x1a\x16.auth.ValidateResponse\x12\x39\n\nCreateUser\x12\x17.auth.CreateUserRequest\x1a\x12.auth.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=20
  _globals['_LOGINREQUEST']._serialized_end=67
  _globals['_TOKENRESPONSE']._serialized_start=69
  _globals['_TOKENRESPONSE']._serialized_end=126
  _globals['_VALIDATEREQUEST']._serialized_start=128
  _globals['_VALIDATEREQUEST']._serialized_end=160
  _globals['_VALIDATERESPONSE']._serialized_start=162
  _globals['_VALIDATERESPONSE']._serialized_end=244
  _globals['_CREATEUSERREQUEST']._serialized_start=246
  _globals['_CREATEUSERREQUEST']._serialized_end=312
  _globals['_USERRESPONSE']._serialized_start=314
  _globals['_USERRESPONSE']._serialized_end=355
  _globals['_AUTHNAVIGATION']._serialized_start=358
  _globals['_AUTHNAVIGATION']._serialized_end=547
# @@protoc_insertion_point(module_scope)
