# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\x1a\x1bgoogle/protobuf/empty.proto\"/\n\x0cLoginRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"9\n\rTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\ntoken_type\x18\x02 \x01(\t\" \n\x0fValidateRequest\x12\r\n\x05token\x18\x01 \x01(\t\"R\n\x10ValidateResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\r\n\x05login\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x10\n\x08is_valid\x18\x04 \x01(\x08\"B\n\x11\x43reateUserRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"\x85\x01\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\x08password\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04role\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x16\n\tis_active\x18\x04 \x01(\x08H\x02\x88\x01\x01\x42\x0b\n\t_passwordB\x07\n\x05_roleB\x0c\n\n_is_active\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\x0e\x44\x65leteResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"5\n\x10UserListResponse\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.auth.UserResponse\"J\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05login\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x11\n\tis_active\x18\x04 \x01(\x08\x32\xf2\x02\n\x0e\x41uthNavigation\x12\x30\n\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.TokenResponse\x12>\n\rValidateToken\x12\x15.auth.ValidateRequest\x1a\x16.auth.ValidateResponse\x12\x39\n\nCreateUser\x12\x17.auth.CreateUserRequest\x1a\x12.auth.UserResponse\x12\x39\n\nUpdateUser\x12\x17.auth.UpdateUserRequest\x1a\x12.auth.UserResponse\x12;\n\nDeleteUser\x12\x17.auth.DeleteUserRequest\x1a\x14.auth.DeleteResponse\x12;\n\tListUsers\x12\x16.google.protobuf.Empty\x1a\x16.auth.UserListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGINREQUEST']._serialized_start=49
  _globals['_LOGINREQUEST']._serialized_end=96
  _globals['_TOKENRESPONSE']._serialized_start=98
  _globals['_TOKENRESPONSE']._serialized_end=155
  _globals['_VALIDATEREQUEST']._serialized_start=157
  _globals['_VALIDATEREQUEST']._serialized_end=189
  _globals['_VALIDATERESPONSE']._serialized_start=191
  _globals['_VALIDATERESPONSE']._serialized_end=273
  _globals['_CREATEUSERREQUEST']._serialized_start=275
  _globals['_CREATEUSERREQUEST']._serialized_end=341
  _globals['_UPDATEUSERREQUEST']._serialized_start=344
  _globals['_UPDATEUSERREQUEST']._serialized_end=477
  _globals['_DELETEUSERREQUEST']._serialized_start=479
  _globals['_DELETEUSERREQUEST']._serialized_end=510
  _globals['_DELETERESPONSE']._serialized_start=512
  _globals['_DELETERESPONSE']._serialized_end=544
  _globals['_USERLISTRESPONSE']._serialized_start=546
  _globals['_USERLISTRESPONSE']._serialized_end=599
  _globals['_USERRESPONSE']._serialized_start=601
  _globals['_USERRESPONSE']._serialized_end=675
  _globals['_AUTHNAVIGATION']._serialized_start=678
  _globals['_AUTHNAVIGATION']._serialized_end=1048
# @@protoc_insertion_point(module_scope)
